import os
# get the top level folder for this project
dir_path = os.path.dirname(os.path.realpath(__file__))

# define environment vaiables
class Config(object):
    # A random key generated by command:
    #   python -c 'import os; print(os.urandom(16))'
    # Variables to configure database
    USERNAME = #Add details
    PASSWORD = #add details'
    HOSTNAME = #add details
    DATABASE = #add details
    
    # Top level folder path
    TOP_FOLDER = dir_path

    # aws credentials
    ACCESS_KEY_ID = 'your access key id'
    SECRET_KEY = 'your password'
    REGION = 'your region'
